# Generated by Django 3.0 on 2019-12-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_historicalfiledata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalFileData',
        ),
    ]
